[package]
name = "flume-monoio"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.0"
futures-util = "0.3.31"
monoio = { version = "0.2.4", features = ["default", "sync"] }

[[bin]]
name = "sync"
path = "src/sync.rs"

[[bin]]
name = "async"
path = "src/async.rs"
